// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRxtouizZmh9NtHgroCJR3VOgeOMEgXtc',
    appId: '1:484256591217:web:159d3038a4e6a706d3dad0',
    messagingSenderId: '484256591217',
    projectId: 'mr-bunapp',
    authDomain: 'mr-bunapp.firebaseapp.com',
    storageBucket: 'mr-bunapp.firebasestorage.app',
    measurementId: 'G-NQ990NB3ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBurE5Q5PDkpJXzeRJ0EAO5x8KaeLJ4ZQQ',
    appId: '1:484256591217:android:3abd289b7d915c5fd3dad0',
    messagingSenderId: '484256591217',
    projectId: 'mr-bunapp',
    storageBucket: 'mr-bunapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASdw57idEysLPMfgOSybIJn1swAIS3x7k',
    appId: '1:484256591217:ios:db4a2e1203402d96d3dad0',
    messagingSenderId: '484256591217',
    projectId: 'mr-bunapp',
    storageBucket: 'mr-bunapp.firebasestorage.app',
    iosBundleId: 'com.example.bunApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASdw57idEysLPMfgOSybIJn1swAIS3x7k',
    appId: '1:484256591217:ios:db4a2e1203402d96d3dad0',
    messagingSenderId: '484256591217',
    projectId: 'mr-bunapp',
    storageBucket: 'mr-bunapp.firebasestorage.app',
    iosBundleId: 'com.example.bunApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRxtouizZmh9NtHgroCJR3VOgeOMEgXtc',
    appId: '1:484256591217:web:3d8d0e78df1eb8c8d3dad0',
    messagingSenderId: '484256591217',
    projectId: 'mr-bunapp',
    authDomain: 'mr-bunapp.firebaseapp.com',
    storageBucket: 'mr-bunapp.firebasestorage.app',
    measurementId: 'G-HTHYXN7L78',
  );
}
