// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKTOfYl5O6p7WI5R0E0ZRZEYhDlvGty9A',
    appId: '1:483327833252:web:957360afce875a3aeda231',
    messagingSenderId: '483327833252',
    projectId: 'diliveryboyapp',
    authDomain: 'diliveryboyapp.firebaseapp.com',
    databaseURL: 'https://diliveryboyapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diliveryboyapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARgUqA39-bZ5kbbw0ZSRjIZ_XI0b_n1U8',
    appId: '1:483327833252:android:73e91e333d9bd5f1eda231',
    messagingSenderId: '483327833252',
    projectId: 'diliveryboyapp',
    databaseURL: 'https://diliveryboyapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diliveryboyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyXcJkE6qWCVomGxlfbVoDSSx0sEii8R8',
    appId: '1:483327833252:ios:11b9540dacc95881eda231',
    messagingSenderId: '483327833252',
    projectId: 'diliveryboyapp',
    databaseURL: 'https://diliveryboyapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diliveryboyapp.appspot.com',
    iosBundleId: 'com.example.bunApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyXcJkE6qWCVomGxlfbVoDSSx0sEii8R8',
    appId: '1:483327833252:ios:11b9540dacc95881eda231',
    messagingSenderId: '483327833252',
    projectId: 'diliveryboyapp',
    databaseURL: 'https://diliveryboyapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diliveryboyapp.appspot.com',
    iosBundleId: 'com.example.bunApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKTOfYl5O6p7WI5R0E0ZRZEYhDlvGty9A',
    appId: '1:483327833252:web:8b88dddb3dd784e6eda231',
    messagingSenderId: '483327833252',
    projectId: 'diliveryboyapp',
    authDomain: 'diliveryboyapp.firebaseapp.com',
    databaseURL: 'https://diliveryboyapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diliveryboyapp.appspot.com',
  );
}
